Add notebook for RF QSO targets selection
desihub/desitarget pull request #664
Opened 2020-12-21 13:33 UTC by echaussidon

Hi, 

I write a jupyter notebook explain how the RF for qso targets selection were generated. 

I also put the scripts for the training in : `desitarget/train`

Files are saved in Nersc at  : `/global/cfs/cdirs/desi/target/analysis/RF`

2020-12-21 13:33 UTC, echaussidon commented
For the review : @geordie666

2020-12-21 19:08 UTC, geordie666 requested changes
@echaussidon: Thanks for your extensive effort! I didn't have time to try the full tutorial, but the initial parts that I did try worked well.

[Documentation tests](https://travis-ci.org/github/desihub/desitarget/builds/750839518) are failing because the `api.rst` file that tracks documentation for [Read The Docs](https://desitarget.readthedocs.io/en/latest/) needs to be update to reflect your new `py/desitarget/train/` directory structure.

In addition to making the changes I've highlighted in the review, you'll also need to update the [`api.rst` file](https://github.com/desihub/desitarget/blob/master/doc/api.rst) in your branch to add the modules in each of your `__init.py__` files. 

Also, in the `api.rst` file, make sure to remove the reference to `.. automodule:: desitarget.train.train_mva_decals` which you are removing as a directory in `py/desitarget/train/`.

Once the documentation (sphinx) tests pass, I'm happy to merge this.

2020-12-21 19:08 UTC, geordie666 commented on py/desitarget/train/train_test_RF/__init__.py
> +desitarget
Title here needs to be `desitarget.train.train_test_RF`.

2020-12-21 19:08 UTC, geordie666 commented on py/desitarget/train/train_test_RF/util/__init__.py
> +desitarget
I think the title here needs to be `desitarget.train.train_test.util`.

2020-12-22 10:19 UTC, echaussidon commented
@geordie666 : I think every thing works now ! I'm not very familiar with api.rst, ect ... 

Thanks for your review.

2020-12-22 14:09 UTC, geordie666 commented
Thanks @echaussidon. And, thanks also for fixing-up all of the code style. I usually address that in my "spare time", but it's definitely good practice to adhere to PEP 8 style. I'll merge this soon.

2020-12-22 14:47 UTC, merged