Implement z-band fiber-total-magnitude bright cut for LRGs
desihub/desitarget pull request #699
Opened 2021-03-29 21:54 UTC by rongpu

This PR replaces the FIBERFLUX_Z bright cut with a FIBERTOTFLUX_Z bright cut to reject shredded bright stars.

2021-03-29 22:08 UTC, geordie666 requested changes
Looks good, just a couple of minor oversights in the `changes.rst` file that you should fix.

Also, please update the wiki with the new bright-end cut.

2021-03-29 22:08 UTC, geordie666 commented on doc/changes.rst
> +* Update the LRG selection for SV3 (The 1% Survey) [`PR #694`_]:
This should be ```[`PR #699`_]```

2021-03-29 22:08 UTC, geordie666 commented on doc/changes.rst
Here you need to add:
```
.. _`PR #699`: https://github.com/desihub/desitarget/pull/699
```

2021-03-29 22:12 UTC, rongpu commented
Thanks @geordie666. I have fixed the link in `changes.rst`.

2021-03-29 22:19 UTC, geordie666 commented
Tests are still failing because you need a blank line between the end of the bullet list and the link. So, between this line:
```
    * Replace the zfiber>16 cut with a zfibertot>16 cut to reject shredded bright stars.
```
and this line:
```
.. _`PR #699`: https://github.com/desihub/desitarget/pull/699
```

That should fix the doc test error.

Thanks! Once you fix that, I'll merge this.

2021-03-30 01:12 UTC, rongpu commented
I've added the blank line. Thanks!

2021-03-30 15:26 UTC, geordie666 approved these changes

2021-03-30 15:26 UTC, merged