Updated backup cuts
desihub/desitarget pull request #766
Opened 2021-10-06 04:50 UTC by apcooper

This PR updates the backup target selection cuts to match the backup program document:
https://www.overleaf.com/project/61116134e46f88886a3367d2

- Add bp-rp based mag thresholds
- Add new backup_giant target class

2021-10-09 18:39 UTC, apcooper commented
@geordie666 I think this is ready for you to take a look, thanks.

2021-10-13 17:00 UTC, geordie666 requested changes
This all looks good @apcooper, thanks. Thanks, in particular, for taking care to be backwards-compatible with `sv3`. I've run a handful of example files using your branch and put them in:
```
/global/cscratch1/sd/adamyers/gaiadr2/1.3.0.dev5218/targets/main/resolve/backup
/global/cscratch1/sd/adamyers/gaiadr2/1.3.0.dev5218/targets/sv3/resolve/backup
```
Everything ran to completion, exactly as I would have expected. I ran with the `--gaiasub` option for `main`, meaning that those results should use Gaia edr3.

I've requested a few minor changes for style and documentation (and also included a question I had about behavior near the Galactic Plane). Once those changes are addressed, I'm certainly happy for this to be merged. Once we merge this, I can run a larger set of example files for people to vet.

2021-10-16 13:26 UTC, apcooper commented on py/desitarget/cuts.py
>      -----
Done.

2021-10-16 13:27 UTC, apcooper commented on py/desitarget/cuts.py
> +    primary &= gaiagmag > 10.0
Done.

2021-10-16 13:27 UTC, apcooper commented on py/desitarget/cuts.py
> +    isbackupbright &= gaiagmag <= 16.0
Done.

2021-10-16 13:27 UTC, apcooper commented on py/desitarget/cuts.py
> +    isbackupgiant &= gaiagmag > 16.0
Done.

2021-10-16 13:44 UTC, apcooper commented on py/desitarget/cuts.py
>      isbackupfaint &= ~in_gal
As you say the original point of those geometric cuts was to keep the target catalog small. The discussion in https://github.com/desihub/desitarget/issues/541 suggests that might not be an issue now? If not, we can probably remove this `~in_gal` cut.

2021-10-16 13:44 UTC, apcooper commented on py/desitarget/cuts.py
>      isbackupveryfaint &= ~in_gal
See comment above.

2021-10-19 21:59 UTC, geordie666 commented
I'm going to leave this open a little longer; @schlafly wants to check some bright-end cuts in G, Bp, Rp, in case of saturation. So we may need to add a few more lines of code before running this.

2021-10-19 22:54 UTC, geordie666 commented
@apcooper : Do Eddie's suggested bright-end cuts look good? If so, I'll add those cuts, merge this PR, and then run an example set of targets. Cori is down tomorrow, so it might be Thursday before we have the files.

2021-10-20 14:39 UTC, apcooper commented
Thanks. Looks OK but I'd like @segasai's opinion.

2021-10-20 23:09 UTC, geordie666 commented
Thanks, all. Unless I hear otherwise, once Cori is back up (or more likely tomorrow) I'll add Eddie's proposed bright limits and merge this PR. 

@apcooper: As Cori will be back up sooner, your-time (I _think_), feel free to beat me to this and add Eddie's limits yourself!

2021-10-22 12:36 UTC, merged